name: socail_network_flutter
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  google_sign_in: ^4.5.1
  shared_preferences: ^0.5.8
  fluttertoast: ^4.0.0
  font_awesome_flutter: ^8.8.1
  intro_views_flutter: "^2.8.1"
  curved_navigation_bar: ^0.3.3
  flutter_speed_dial: ^1.2.5
  image_picker: ^0.6.7+4
  video_player: ^0.10.11+2
  chewie: ^0.9.10
  timeago: ^2.0.26
  flutter_focus_watcher: ^0.0.1
  keyboard_attachable: ^1.0.3
  flutter_share_me: ^0.9.1

  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/LoginPage/
    - images/ProfilePage/
    - images/ProfileComp/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
#    - family: Montserrat
#      fonts:
#        - asset: fonts/Montserrat/Monsterrat-Regular.ttf
